image: ghcr.io/jethub-homeassistant/{arch}-base-python
build_from:
  aarch64: "ghcr.io/jethub-homeassistant/aarch64-base:"
  armv7: "ghcr.io/jethub-homeassistant/armv7-base:"
  armhf: "ghcr.io/jethub-homeassistant/armhf-base:"
  amd64: "ghcr.io/jethub-homeassistant/amd64-base:"
  i386: "ghcr.io/jethub-homeassistant/i386-base:"
cosign:
  base_identity: https://github.com/jethub-homeassistant/docker-base/.*
  identity: https://github.com/jethub-homeassistant/docker-base/.*
args:
  PYTHON_VERSION: 3.11.13
  PIP_VERSION: 25.1.1
  CERT_IDENTITY: pablogsal@python.org
  CERT_OIDC_ISSUER: https://accounts.google.com
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/jethub-homeassistant/docker-base
