image: ghcr.io/jethub-homeassistant/{arch}-base-python
build_from:
  aarch64: "ghcr.io/jethub-homeassistant/aarch64-base:"
  armv7: "ghcr.io/jethub-homeassistant/armv7-base:"
  armhf: "ghcr.io/jethub-homeassistant/armhf-base:"
  amd64: "ghcr.io/jethub-homeassistant/amd64-base:"
  i386: "ghcr.io/jethub-homeassistant/i386-base:"
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
cosign:
  base_identity: https://github.com/jethub-homeassistant/docker-base/.*
  identity: https://github.com/jethub-homeassistant/docker-base/.*
args:
  PYTHON_VERSION: 3.9.17
  PIP_VERSION: 23.1.2
  GPG_KEY: E3FF2839C048B25C084DEBE9B26995E310250568
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/jethub-homeassistant/docker-base
